package __PACKAGE__

import android.content.Context
import android.content.SharedPreferences
import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import com.facebook.react.modules.network.CustomClientBuilder
import com.facebook.react.modules.network.NetworkingModule
import com.facebook.react.modules.websocket.WebSocketModule
import com.facebook.react.uimanager.ViewManager
import java.net.InetAddress
import java.net.Socket
import java.security.KeyStore
import java.security.MessageDigest
import java.security.cert.CertificateException
import java.security.cert.X509Certificate
import javax.net.ssl.HostnameVerifier
import javax.net.ssl.SSLContext
import javax.net.ssl.SSLEngine
import javax.net.ssl.SSLSession
import javax.net.ssl.SSLSocket
import javax.net.ssl.TrustManagerFactory
import javax.net.ssl.X509ExtendedTrustManager
import javax.net.ssl.X509TrustManager
import okhttp3.internal.tls.OkHostnameVerifier

/**
 * Trust for the Control4 Director's self-signed certificate, applied to React
 * Native's fetch and WebSocket clients (generated by plugins/with-director-trust).
 *
 * - Certificates the system trusts are accepted as usual (Control4 cloud).
 * - Otherwise, only for a private-LAN IP literal: the leaf certificate is
 *   pinned the first time it's seen (trust on first use) and must match on
 *   every later connection. Anything else is rejected.
 * - The Director's cert names the controller, not its IP, so hostname
 *   verification accepts a pinned cert for its host.
 */
object DirectorTrust {
  private const val PREFS = "director_trust"
  private lateinit var prefs: SharedPreferences

  fun install(context: Context) {
    prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
    val trustManager = PinningTrustManager(systemTrustManager())
    val sslContext = SSLContext.getInstance("TLS").apply { init(null, arrayOf(trustManager), null) }
    val verifier = PinningHostnameVerifier()
    val builder = CustomClientBuilder { b ->
      b.sslSocketFactory(sslContext.socketFactory, trustManager)
      b.hostnameVerifier(verifier)
    }
    NetworkingModule.setCustomClientBuilder(builder)
    WebSocketModule.setCustomClientBuilder(builder)
  }

  fun clearPins() {
    prefs.edit().clear().apply()
  }

  private fun pinKey(host: String) = "pin:$host"

  internal fun fingerprint(cert: X509Certificate): String =
    MessageDigest.getInstance("SHA-256").digest(cert.encoded).joinToString(":") { "%02X".format(it) }

  internal fun pinned(host: String): String? = prefs.getString(pinKey(host), null)

  internal fun isPrivateIpLiteral(host: String): Boolean {
    if (!Regex("""^\d{1,3}(\.\d{1,3}){3}$""").matches(host)) return false
    return try {
      val addr = InetAddress.getByName(host)
      addr.isSiteLocalAddress || addr.isLoopbackAddress
    } catch (e: Exception) {
      false
    }
  }

  /** Accept a self-signed leaf for [host] if it matches the pin (or pin it). */
  internal fun checkPinned(host: String?, chain: Array<out X509Certificate>) {
    if (host == null || !isPrivateIpLiteral(host) || chain.isEmpty()) {
      throw CertificateException("Untrusted certificate for ${host ?: "unknown host"}")
    }
    val actual = fingerprint(chain[0])
    val expected = pinned(host)
    if (expected == null) {
      prefs.edit().putString(pinKey(host), actual).apply()
    } else if (expected != actual) {
      throw CertificateException(
        "Director certificate for $host changed (expected $expected, got $actual). " +
          "Sign out and sign in again to trust a replaced controller."
      )
    }
  }

  private fun systemTrustManager(): X509TrustManager {
    val factory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm())
    factory.init(null as KeyStore?)
    return factory.trustManagers.filterIsInstance<X509TrustManager>().first()
  }

  private class PinningTrustManager(private val system: X509TrustManager) : X509ExtendedTrustManager() {
    override fun checkServerTrusted(chain: Array<out X509Certificate>, authType: String, socket: Socket?) {
      try {
        system.checkServerTrusted(chain, authType)
      } catch (e: CertificateException) {
        checkPinned((socket as? SSLSocket)?.handshakeSession?.peerHost, chain)
      }
    }

    override fun checkServerTrusted(chain: Array<out X509Certificate>, authType: String, engine: SSLEngine?) {
      try {
        system.checkServerTrusted(chain, authType)
      } catch (e: CertificateException) {
        checkPinned(engine?.handshakeSession?.peerHost, chain)
      }
    }

    // No peer host available: system trust only.
    override fun checkServerTrusted(chain: Array<out X509Certificate>, authType: String) =
      system.checkServerTrusted(chain, authType)

    override fun checkClientTrusted(chain: Array<out X509Certificate>, authType: String, socket: Socket?) =
      system.checkClientTrusted(chain, authType)

    override fun checkClientTrusted(chain: Array<out X509Certificate>, authType: String, engine: SSLEngine?) =
      system.checkClientTrusted(chain, authType)

    override fun checkClientTrusted(chain: Array<out X509Certificate>, authType: String) =
      system.checkClientTrusted(chain, authType)

    override fun getAcceptedIssuers(): Array<X509Certificate> = system.acceptedIssuers
  }

  private class PinningHostnameVerifier : HostnameVerifier {
    override fun verify(hostname: String, session: SSLSession): Boolean {
      if (OkHostnameVerifier.verify(hostname, session)) return true
      val leaf = session.peerCertificates.firstOrNull() as? X509Certificate ?: return false
      val expected = pinned(hostname) ?: return false
      return isPrivateIpLiteral(hostname) && expected == fingerprint(leaf)
    }
  }
}

/** JS access: NativeModules.DirectorTrust.clearPins() when signing in/out. */
class DirectorTrustModule(context: ReactApplicationContext) : ReactContextBaseJavaModule(context) {
  override fun getName() = "DirectorTrust"

  @ReactMethod
  fun clearPins(promise: Promise) {
    DirectorTrust.clearPins()
    promise.resolve(null)
  }
}

class DirectorTrustPackage : ReactPackage {
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> =
    listOf(DirectorTrustModule(reactContext))

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> = emptyList()
}
